- name: create {{ release }} undercloud upgrade script
  template:
    src: templates/fast-forward-upgrade/undercloud_upgrade.sh.j2
    dest: "{{ working_dir }}/undercloud_upgrade_{{ release }}.sh"
    mode: 0775
  vars:
    query: "tripleo_repos[?release=='{{release}}'].args"
    cmd_args: "{{ ffu_undercloud_repo_args | json_query(query) }}"
