- name: overcloud config download
  shell: |
    source {{ undercloud_rc }}
    openstack overcloud config download --name {{ overcloud_stack_name }}
  register: config_download

- name: set overcloud_config_dir fact.
  set_fact:
    overcloud_config_dir: "{{ config_download.stdout | regex_search('(/.*tripleo.*)')}}"
