---
- name: run deploy_steps_playbook playbook
  shell: |
    source {{ undercloud_rc }}
    ansible-playbook -i /usr/bin/tripleo-ansible-inventory {{ overcloud_config_dir }}/deploy_steps_playbook.yaml
