---
- name: register repo file location
  become: true
  find:
      use_regex: yes
      patterns: 'rhos-release-[0-9]+.*'
      paths:
        - '/etc/yum.repos.d/'
  register: result

- name: register puddle repo url
  shell: |
     grep -B2 enabled=1 {{ result.files[0]['path'] }} | grep -m1 puddle | sed -E "s/.*(http.*[0-9]-RHEL-.\/).*/\1/"
  register: repourl

- name: get container images yaml files
  get_url:
    url: "{{ repourl.stdout }}/latest_containers/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - docker-osp12.yaml
    - overcloud_containers.yaml

- name: download container images
  shell: |
    source ~/stackrc
    openstack overcloud container image upload --verbose --config-file ~/overcloud_containers.yaml

- name: use local registry
  replace:
    dest: ~/docker-osp12.yaml
    regexp: "  DockerNamespace:.*"
    replace: "  DockerNamespace: {{ ansible_br_ctlplane.ipv4.address }}:8787/rhosp12"
