---
- name: register instances running on {{ node_name }}
  shell: |
    source {{ overcloud_rc }}
    openstack server list --host {{ hostvars[node_name].ansible_fqdn }} -f json | jq -r -c '.[] | select(.Status | contains("ACTIVE") or contains("PAUSED")) | .Name'
  register: node_instances

- name: create pre upgrade script for {{ node_name }}
  template:
    src: node_upgrade_pre.sh.j2
    dest: ~/{{ node_name }}_upgrade_pre.sh

- name: create script for upgrading {{ node_name }}
  template:
    src: node_upgrade.sh.j2
    dest: ~/{{ node_name }}_upgrade.sh

- name: create post upgrade script for {{ node_name }}
  template:
    src: node_upgrade_post.sh.j2
    dest: ~/{{ node_name }}_upgrade_post.sh
