---
- name: reboot the undercloud
  shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  become_user: root
  tags: undercloud_reboot

- block:
      - name: waiting for the undercloud to be available
        become: no
        wait_for:
            port: 22
            host: "{{ ansible_ssh_host }}"
            search_regex: OpenSSH
            delay: 10
        delegate_to: localhost
        when: "'hypervisor' not in groups and 'virthost' not in groups"

      - name: waiting for the undercloud to be available
        become: no
        wait_for:
            port: 22
            host: "{{ ansible_ssh_host }}"
            search_regex: OpenSSH
            delay: 10
        delegate_to: hypervisor
        when: "'hypervisor' in groups"

      - name: waiting for the undercloud to be available
        become: no
        wait_for:
            port: 22
            host: "{{ ansible_ssh_host }}"
            search_regex: OpenSSH
            delay: 10
        delegate_to: virthost
        when: "'virthost' in groups"
  tags: undercloud_reboot
