---
- name: start ping test before major upgrade
  include: ../common/l3_agent_connectivity_check_start_script.yml

- name: get L3 agent hosting a router
  include: ../common/l3_agent_failover_check_pre_script.yml

- name: run overcloud major upgrade in each of the roles/hostgroups
  shell: "bash {{ overcloud_upgrade_run_script_base }}-{{ item }}.sh &> {{ working_dir }}/overcloud_upgrade_run_{{ item }}.log"
  with_items:
      - "{{ oc_roles|default('all') }}"
  register: overcloud_upgrade_nodes
  ignore_errors: yes

- name: was the overcloud upgrade composable step successful.
  fail: msg="Overcloud upgrade composable step failed... :("
  with_items: "{{ overcloud_upgrade_nodes.results }}"
  when: item.rc != 0

- name: check packet loss ratio after major upgrade
  include: ../common/l3_agent_connectivity_check_stop_script.yml

- name: check if router failover happened
  include: ../common/l3_agent_failover_check_post_script.yml
